[uwsgi]
# uWSGI settings
master = true
processes = 2                                 # Number of processes
threads = 8                                   # Number of threads per process
vacuum = true                                 # Clean up socket files on exit
module=wsgi:application
enable-threads = true